import { t } from 'ttag';
import ReactMarkdown from 'react-markdown';
import ExternalLink from '../../../../../ExternalLink/ExternalLink';

const IOLULCMarkdown = () => t`
The **10m Annual Land Use Land Cover (LULC) Map** is produced by Impact Observatory, Microsoft, and Esri collaboratively. The data collection is derived from ESA Sentinel-2 imagery at 10m resolution globally using Impact Observatory's state of the art deep learning AI land classification model which is trained by billions of human-labeled image pixels. There are 9 LULC classes generated by the algorithm, including Built, Crops, Trees, Water, Rangeland, Flooded Vegetation, Snow/Ice, Bare Ground, and Clouds.

**Coverage**: Global land area

**Data Availability**: 2017 - 2021

**Spatial resolution**: 10 m
`;

const IOLULCTooltip = () => (
  <div>
    <div className="data-source-group-tooltip-description">
      <ReactMarkdown source={IOLULCMarkdown()} />
    </div>
    <div className="data-source-group-tooltip-credits">
      <div>{t`Credits:`}</div>
      <div>
        <ExternalLink href="https://www.impactobservatory.com/">Impact Observatory</ExternalLink>
      </div>
    </div>
  </div>
);

export { IOLULCTooltip };
